### ISSUE TITLE
2-3 white pixels on top

### ISSUE THREAD

**Issue by DoctorJellyface** [chpii/Headerbar#7]
I used the window decoration tweak in step 4, but I get these "white line" on the top of the window:
![snimka obrazovky z 2015-02-28 17 38 34](https://cloud.githubusercontent.com/assets/7472425/6426914/e3cc6894-bf70-11e4-9f07-e77e429dab18.png)
It's hard to see, but it's there even when the window is maximised:
![snimka obrazovky z 2015-02-28 17 38 58](https://cloud.githubusercontent.com/assets/7472425/6426918/f511c6f8-bf70-11e4-8677-f5582c5bd072.png)
I could live with it, but look what happens after installing the dark theme extension:
![snimka obrazovky z 2015-02-28 17 45 17](https://cloud.githubusercontent.com/assets/7472425/6426941/9b7f5cc6-bf71-11e4-93e1-e2b19bca9f7b.png)
I know it's a minor issue, but an annoying one. Anyway, keep up the great work!

**Comment by DoctorJellyface** [comment]
Also, this is what it looks like when unfocused:
![snimka obrazovky z 2015-02-28 17 52 18](https://cloud.githubusercontent.com/assets/7472425/6426969/8fb7169e-bf72-11e4-84dd-8198e7275c71.png)

**Comment by chpii** [comment]
https://github.com/chpii/Headerbar#dark-theme

- Install dark window decoration extension
- **Enter about:config in adress field to access advanced preferences**
- **Change extensions.gnome-theme-tweak.dark-variant key to 1 to switch dark theme on**

Have you done each step of these?

**Comment by DoctorJellyface** [comment]
I didn't do the second two. I just wanted the extension there so I could use it when I needed to, and I noticed that it does that. I just posted it because you can see the bar better there.

**Comment by chpii** [comment]
Yes, I understand.

This is because original author of extension decided to handle decorations separately, probably for use with other themes than GNOME.

I will look to it later at the end of next week (assuming things will go well IRL) and see what I can do.

**Comment by DoctorJellyface** [comment]
Thanks man.

**Comment by chpii** [comment]
I just updated to GNOME 3.15.91 and there is no need to install any theme for decorations.
Now themes for decorations are taken from GTK+ theme, that does have same semi-transparent borders for all windows. Luckily we don't need to change anything, because it has same rounding as for any other window.

![2015-03-16 01-47-34](https://cloud.githubusercontent.com/assets/7461424/6658830/79470eba-cb7e-11e4-9445-405b2008bd8d.png)

**Comment by DoctorJellyface** [comment]
Cool! Though keep in mind that some distros will stick to <= 3.14 for some time unfortunately.

What distro are you on BTW? I'm on Arch, and I would really like to be on the dev version, but I didn't find anything.

**Comment by chpii** [comment]
I'm on Arch too.

You can update to GNOME 3.15.91 if you enable `[gnome-unstable]` repo in `/etc/pacman.conf`:

    [gnome-unstable]
    Include = /etc/pacman.d/mirrorlist

    #[testing]
    #Include = /etc/pacman.d/mirrorlist

    [core]
    Include = /etc/pacman.d/mirrorlist

I have not spotted any bug in GNOME itself. But I should warn you that you can't resize with left clicking on right and bottom edges of Firefox with new userstyle.

Either you have resizing on all edges or no rounded corners.

**Comment by DoctorJellyface** [comment]
OH YOU PUT THAT ON THE TOP!

The `[gnome-unstable]` sat in my `pacman.conf` for quite some time, but at the bottom of it.

**Comment by DoctorJellyface** [comment]
Random thought - is there any way to pass different window dimensions to the window manager? I think the fault could be there, since it adds some pixels at the top.

**Comment by chpii** [comment]
I don't see any pixels on top, except shadow and border that are drawn by mutter.

What I know is Firefox can't do RGBA windows yet (it's using GTK+-2, but not sure if GTK+-3 port can do it either), so we can't do real client-side decorations and setting [_NET_FRAME_EXTENTS](http://standards.freedesktop.org/wm-spec/wm-spec-1.5.html#idm140200472552416) hint to mark regions that are reserved for our decorations. And that is not a clear picture, maybe we need to handle resizing and whatnot ourselves too, or with what GTK+ provides.

We can try getting and setting dimensions, but the only code that does something remotely close to this is in HTitle, code of which I don't have understanding.

By the way there is bug which may be caused by this userstyle:
https://github.com/seleznev/firefox-extension-htitle/issues/60

**Comment by chpii** [comment]
I disabled rounded corners by default for now, you can uncomment relevant lines in userstyle.

About original bug, it's not mine. [I asked about it earlier](https://github.com/gnome-integration-team/firefox-gnome/issues/37#issuecomment-64942911).

For older versions of GNOME it is possible to make it not depend on metacity theme too, but it will have even weirder resizing problems (you can also reproduce this by resizing window by vertical axis very fast) or no rounded corners.

I am open to suggestions what is better, but I believe "Don't touch what already works" will be popular opinion amongst users.

**Comment by chpii** [comment]
Oh, yeah about unfocused state: https://github.com/gnome-integration-team/firefox-gnome/issues/82#issuecomment-8191561

**Comment by DoctorJellyface** [comment]
> I don't see any pixels on top, except shadow and border that are drawn by mutter.

Oh, I meant the padding. Thought the problem might have been there, looks like it isn't.
